### PR TITLE
Fixing tests; reordering imports; making sibling imports relative

### PR DESCRIPTION
**Pull request by lselker13**

### CODE REVIEW

**Review by LucioMelito — APPROVED** [review]
I have a slight preference for keeping the ordering of imports alphabetical, but what's the rationale for changing it?

**Comment by lselker13** [comment]
> @LucioMelito Thanks for the review!

Import ordering is in the [Python style guide](https://peps.python.org/pep-0008/#imports). I also prefer this ordering because different kinds of imports mean different things (built-in imports don't mean much, external non-builtins indicate third party dependencies, internal imports indicate how different cider files depend on each other). I noticed this because I was making sibling imports relative and it was not straightforward to figure out which imports are sibling imports, not yet knowing the names of all the Cider modules. This ordering makes it easy to see at a glance what other Cider files are being imported. But I agree with you that within a category, imports should be alphabetical!

**Comment by LucioMelito** [comment]
> 

Sounds great, thanks!

**Review by emilylaiken — APPROVED** [review]
Looks great! Thanks Leo.

**Review by satejsoman — APPROVED** [review]

**Pull request merged**
